##### RUN SECTION #####
run:
  deadline: 5m
  module-download-mode: readonly
  skip-dirs:
    - templates
    - cmd


#### OUTPUT SECTION ######
output:
  format: colored-line-number

  print-issued-lines: true

  print-linter-name: true

#### issues  ######
issues:
  exclude:
    - ifElseChain
    - singleCaseSwitch
    - assignOp
    - unlambda


#### linters settings  ######
linters-settings:
  errcheck:
    check-type-assertions: false
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - revive
    - gocritic
    - stylecheck
    - gosec
    - unconvert
    - ineffassign
    - unconvert
    - gofmt
    - gosimple
    - staticcheck
  fast: false