// Code generated by go-swagger; DO NOT EDIT.

// Package server Solarsteinn
//
//	TODO
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//	License: MIT
//	Contact: <infra@gateway.fm>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package server
